### ISSUE TITLE
documentation qleiade qualitek

### ISSUE THREAD

**Issue by qleiade** [la-cite-des-formations/qleiade_doc#2]

**Comment by claudeagier** [comment]
qleiade_doc mis en public pour avoir la fonctionnalité wiki

**Comment by claudeagier** [comment]
récupération de mon rapport de stage

**Comment by claudeagier** [comment]
remaniement et mise en ligne

**Comment by claudeagier** [comment]
cahier des charges ok

**Comment by claudeagier** [comment]
analyse globale ok

**Comment by claudeagier** [comment]
daemon en place mais à compléter

**Comment by claudeagier** [comment]
site web à faire

**Comment by claudeagier** [comment]
Home à améliorer au fil de l'eau.
Pour l'instant elle contient une liste de liens.

**Comment by claudeagier** [comment]
doc technique site web premier jet ok

**Comment by claudeagier** [comment]
doc utilisateur à compléter à l'usage

**Comment by claudeagier** [comment]
je n'aurai pas d'issue défini pour compléter les doc. Elles seront complétées au fur et à mesure.
peut être une issue à faire pour tout valider en fin de contrat
